site_name: ERP Help
theme:
  name: readthedocs
  locale: vi
nav:
  - 'index.md'
  - Sản xuất:
    - 'manufacturing/production-order.md'
    - 'manufacturing/labor-hed.md'
    - 'manufacturing/reporting.md'
    - 'manufacturing/mobile-device.md'
